2016-11-24 11:22:03,115 [INFO] from play.core.server.NettyServer in pool-6-thread-4 - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
2016-11-24 11:24:45,871 [INFO] from application in ForkJoinPool-1-worker-1 - ApplicationTimer demo: Starting application at 2016-11-24T10:24:45.862Z.
2016-11-24 11:24:46,127 [INFO] from application in ForkJoinPool-1-worker-1 - Resolving database...
2016-11-24 11:24:46,201 [INFO] from application in ForkJoinPool-1-worker-1 - ReactiveMongoApi successfully configured with DB 'gdeed'! Servers:
		[localhost:27017]
2016-11-24 11:24:46,256 [INFO] from play.api.Play in ForkJoinPool-1-worker-1 - Application started (Dev)
2016-11-24 11:24:47,475 [ERROR] from application in application-akka.actor.default-dispatcher-4 - 

! @726n72ln6 - Internal server error, for (GET) [/events] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: (,List())]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:269)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:195)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:98)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$$anonfun$tryCompleteWith$1.apply(Promise.scala:76)
	at scala.concurrent.Promise$$anonfun$tryCompleteWith$1.apply(Promise.scala:76)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: (,List())
	at scala.sys.package$.error(package.scala:27)
	at reactivemongo.play.json.JSONSerializationPack$.deserialize(package.scala:470)
	at reactivemongo.play.json.JSONSerializationPack$.deserialize(package.scala:437)
	at reactivemongo.api.SerializationPack$class.readAndDeserialize(serializationpack.scala:28)
	at reactivemongo.play.json.JSONSerializationPack$.readAndDeserialize(package.scala:437)
	at reactivemongo.core.protocol.ReplyDocumentIterator$$anon$1.next(protocol.scala:377)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$6.apply(cursor.scala:646)
	at scala.util.Try$.apply(Try.scala:192)
	at reactivemongo.api.DefaultCursor$Impl$class.go$1(cursor.scala:646)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldWhileM$2.apply(cursor.scala:666)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldWhileM$2.apply(cursor.scala:666)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldBulksM$2.apply(cursor.scala:630)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldBulksM$2.apply(cursor.scala:628)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses.procResp(cursor.scala:792)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses$$anonfun$procResponses$3.apply(cursor.scala:828)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses$$anonfun$procResponses$3.apply(cursor.scala:827)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 13 common frames omitted
2016-11-24 11:38:55,487 [ERROR] from application in netty-event-loop-5 - 

! @726n8p295 - Internal server error, for (GET) [/events] ->
 
play.sbt.PlayExceptions$CompilationException: Compilation error[No Json serializer as JsObject found for type Unit. Try to implement an implicit OWrites or OFormat for this type.]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at scala.util.Either$LeftProjection.map(Either.scala:377)
	at play.sbt.run.PlayReload$.compile(PlayReload.scala:17)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61)
	at play.runsupport.Reloader$$anonfun$reload$1.apply(Reloader.scala:338)
	at play.runsupport.Reloader$$anon$3.run(Reloader.scala:43)
	at java.security.AccessController.doPrivileged(Native Method)
	at play.runsupport.Reloader$.play$runsupport$Reloader$$withReloaderContextClassLoader(Reloader.scala:39)
	at play.runsupport.Reloader.reload(Reloader.scala:336)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:118)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:116)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2016-11-24 11:39:12,186 [ERROR] from application in netty-event-loop-5 - 

! @726n9011c - Internal server error, for (GET) [/events] ->
 
play.sbt.PlayExceptions$CompilationException: Compilation error[Cannot write an instance of List[models.Event] to HTTP response. Try to define a Writeable[List[models.Event]]]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at scala.util.Either$LeftProjection.map(Either.scala:377)
	at play.sbt.run.PlayReload$.compile(PlayReload.scala:17)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61)
	at play.runsupport.Reloader$$anonfun$reload$1.apply(Reloader.scala:338)
	at play.runsupport.Reloader$$anon$3.run(Reloader.scala:43)
	at java.security.AccessController.doPrivileged(Native Method)
	at play.runsupport.Reloader$.play$runsupport$Reloader$$withReloaderContextClassLoader(Reloader.scala:39)
	at play.runsupport.Reloader.reload(Reloader.scala:336)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:118)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:116)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2016-11-24 11:39:34,369 [INFO] from application in ForkJoinPool-4-worker-13 - ReactiveMongoApi stopping...
2016-11-24 11:39:34,417 [INFO] from application in ForkJoinPool-4-worker-11 - ReactiveMongoApi connections stopped. [Success(Closed)]
2016-11-24 11:39:34,470 [INFO] from application in ForkJoinPool-4-worker-13 - ApplicationTimer demo: Stopping application at 2016-11-24T10:39:34.470Z after 889s.
2016-11-24 11:39:34,655 [INFO] from application in application-akka.actor.default-dispatcher-2 - ApplicationTimer demo: Starting application at 2016-11-24T10:39:34.654Z.
2016-11-24 11:39:34,764 [INFO] from application in application-akka.actor.default-dispatcher-2 - Resolving database...
2016-11-24 11:39:34,776 [INFO] from application in application-akka.actor.default-dispatcher-2 - ReactiveMongoApi successfully configured with DB 'gdeed'! Servers:
		[localhost:27017]
2016-11-24 11:39:34,785 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-2 - Application started (Dev)
2016-11-24 11:39:34,916 [ERROR] from application in application-akka.actor.default-dispatcher-2 - 

! @726n918hj - Internal server error, for (GET) [/events] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: (,List())]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:269)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:195)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:98)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$$anonfun$tryCompleteWith$1.apply(Promise.scala:76)
	at scala.concurrent.Promise$$anonfun$tryCompleteWith$1.apply(Promise.scala:76)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: (,List())
	at scala.sys.package$.error(package.scala:27)
	at reactivemongo.play.json.JSONSerializationPack$.deserialize(package.scala:470)
	at reactivemongo.play.json.JSONSerializationPack$.deserialize(package.scala:437)
	at reactivemongo.api.SerializationPack$class.readAndDeserialize(serializationpack.scala:28)
	at reactivemongo.play.json.JSONSerializationPack$.readAndDeserialize(package.scala:437)
	at reactivemongo.core.protocol.ReplyDocumentIterator$$anon$1.next(protocol.scala:377)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$6.apply(cursor.scala:646)
	at scala.util.Try$.apply(Try.scala:192)
	at reactivemongo.api.DefaultCursor$Impl$class.go$1(cursor.scala:646)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldWhileM$2.apply(cursor.scala:666)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldWhileM$2.apply(cursor.scala:666)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldBulksM$2.apply(cursor.scala:630)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldBulksM$2.apply(cursor.scala:628)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses.procResp(cursor.scala:792)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses$$anonfun$procResponses$3.apply(cursor.scala:828)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses$$anonfun$procResponses$3.apply(cursor.scala:827)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 13 common frames omitted
2016-11-24 11:41:06,481 [ERROR] from application in application-akka.actor.default-dispatcher-6 - 

! @726n96e3c - Internal server error, for (GET) [/events] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: (,List())]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:269)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:195)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:98)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$$anonfun$tryCompleteWith$1.apply(Promise.scala:76)
	at scala.concurrent.Promise$$anonfun$tryCompleteWith$1.apply(Promise.scala:76)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: (,List())
	at scala.sys.package$.error(package.scala:27)
	at reactivemongo.play.json.JSONSerializationPack$.deserialize(package.scala:470)
	at reactivemongo.play.json.JSONSerializationPack$.deserialize(package.scala:437)
	at reactivemongo.api.SerializationPack$class.readAndDeserialize(serializationpack.scala:28)
	at reactivemongo.play.json.JSONSerializationPack$.readAndDeserialize(package.scala:437)
	at reactivemongo.core.protocol.ReplyDocumentIterator$$anon$1.next(protocol.scala:377)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$6.apply(cursor.scala:646)
	at scala.util.Try$.apply(Try.scala:192)
	at reactivemongo.api.DefaultCursor$Impl$class.go$1(cursor.scala:646)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldWhileM$2.apply(cursor.scala:666)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldWhileM$2.apply(cursor.scala:666)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldBulksM$2.apply(cursor.scala:630)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldBulksM$2.apply(cursor.scala:628)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses.procResp(cursor.scala:792)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses$$anonfun$procResponses$3.apply(cursor.scala:828)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses$$anonfun$procResponses$3.apply(cursor.scala:827)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 13 common frames omitted
2016-11-24 11:41:12,198 [ERROR] from application in netty-event-loop-5 - 

! @726n96mf9 - Internal server error, for (GET) [/events] ->
 
play.sbt.PlayExceptions$CompilationException: Compilation error[polymorphic expression cannot be instantiated to expected type;
 found   : [A]play.api.libs.iteratee.Enumeratee[A,play.api.libs.json.JsValue]
 required: models.Event => ?]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at scala.util.Either$LeftProjection.map(Either.scala:377)
	at play.sbt.run.PlayReload$.compile(PlayReload.scala:17)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61)
	at play.runsupport.Reloader$$anonfun$reload$1.apply(Reloader.scala:338)
	at play.runsupport.Reloader$$anon$3.run(Reloader.scala:43)
	at java.security.AccessController.doPrivileged(Native Method)
	at play.runsupport.Reloader$.play$runsupport$Reloader$$withReloaderContextClassLoader(Reloader.scala:39)
	at play.runsupport.Reloader.reload(Reloader.scala:336)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:118)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:116)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2016-11-24 11:44:26,428 [INFO] from application in ForkJoinPool-4-worker-11 - ReactiveMongoApi stopping...
2016-11-24 11:44:26,438 [INFO] from application in ForkJoinPool-4-worker-7 - ReactiveMongoApi connections stopped. [Success(Closed)]
2016-11-24 11:44:26,465 [INFO] from application in ForkJoinPool-4-worker-11 - ApplicationTimer demo: Stopping application at 2016-11-24T10:44:26.465Z after 292s.
2016-11-24 11:44:26,594 [INFO] from application in application-akka.actor.default-dispatcher-5 - ApplicationTimer demo: Starting application at 2016-11-24T10:44:26.593Z.
2016-11-24 11:44:26,667 [INFO] from application in application-akka.actor.default-dispatcher-5 - Resolving database...
2016-11-24 11:44:26,674 [INFO] from application in application-akka.actor.default-dispatcher-5 - ReactiveMongoApi successfully configured with DB 'gdeed'! Servers:
		[localhost:27017]
2016-11-24 11:44:26,679 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-5 - Application started (Dev)
2016-11-24 11:44:26,817 [ERROR] from application in application-akka.actor.default-dispatcher-6 - 

! @726n9hoci - Internal server error, for (GET) [/events] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: (,List())]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:269)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:195)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:98)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$$anonfun$tryCompleteWith$1.apply(Promise.scala:76)
	at scala.concurrent.Promise$$anonfun$tryCompleteWith$1.apply(Promise.scala:76)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: (,List())
	at scala.sys.package$.error(package.scala:27)
	at reactivemongo.play.json.JSONSerializationPack$.deserialize(package.scala:470)
	at reactivemongo.play.json.JSONSerializationPack$.deserialize(package.scala:437)
	at reactivemongo.api.SerializationPack$class.readAndDeserialize(serializationpack.scala:28)
	at reactivemongo.play.json.JSONSerializationPack$.readAndDeserialize(package.scala:437)
	at reactivemongo.core.protocol.ReplyDocumentIterator$$anon$1.next(protocol.scala:377)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$6.apply(cursor.scala:646)
	at scala.util.Try$.apply(Try.scala:192)
	at reactivemongo.api.DefaultCursor$Impl$class.go$1(cursor.scala:646)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldWhileM$2.apply(cursor.scala:666)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldWhileM$2.apply(cursor.scala:666)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldBulksM$2.apply(cursor.scala:630)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldBulksM$2.apply(cursor.scala:628)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses.procResp(cursor.scala:792)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses$$anonfun$procResponses$3.apply(cursor.scala:828)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses$$anonfun$procResponses$3.apply(cursor.scala:827)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 13 common frames omitted
2016-11-24 11:45:21,558 [INFO] from application in application-akka.actor.default-dispatcher-3 - Resolving database...
2016-11-24 11:53:42,242 [INFO] from application in ForkJoinPool-4-worker-7 - ReactiveMongoApi stopping...
2016-11-24 11:53:42,256 [INFO] from application in ForkJoinPool-4-worker-1 - ReactiveMongoApi connections stopped. [Success(Closed)]
2016-11-24 11:53:42,273 [INFO] from application in ForkJoinPool-4-worker-7 - ApplicationTimer demo: Stopping application at 2016-11-24T10:53:42.273Z after 556s.
2016-11-24 11:53:42,429 [INFO] from application in application-akka.actor.default-dispatcher-7 - ApplicationTimer demo: Starting application at 2016-11-24T10:53:42.428Z.
2016-11-24 11:53:42,511 [INFO] from application in application-akka.actor.default-dispatcher-7 - Resolving database...
2016-11-24 11:53:42,522 [INFO] from application in application-akka.actor.default-dispatcher-7 - ReactiveMongoApi successfully configured with DB 'gdeed'! Servers:
		[localhost:27017]
2016-11-24 11:53:42,527 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-7 - Application started (Dev)
2016-11-24 11:54:21,370 [INFO] from application in ForkJoinPool-4-worker-1 - ReactiveMongoApi stopping...
2016-11-24 11:54:21,377 [INFO] from application in ForkJoinPool-4-worker-13 - ReactiveMongoApi connections stopped. [Success(Closed)]
2016-11-24 11:54:21,390 [INFO] from application in ForkJoinPool-4-worker-1 - ApplicationTimer demo: Stopping application at 2016-11-24T10:54:21.390Z after 39s.
2016-11-24 11:54:21,515 [INFO] from application in application-akka.actor.default-dispatcher-4 - ApplicationTimer demo: Starting application at 2016-11-24T10:54:21.514Z.
2016-11-24 11:54:21,585 [INFO] from application in application-akka.actor.default-dispatcher-4 - Resolving database...
2016-11-24 11:54:21,592 [INFO] from application in application-akka.actor.default-dispatcher-4 - ReactiveMongoApi successfully configured with DB 'gdeed'! Servers:
		[localhost:27017]
2016-11-24 11:54:21,597 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-4 - Application started (Dev)
2016-11-24 11:54:21,727 [ERROR] from application in application-akka.actor.default-dispatcher-2 - 

! @726napkdl - Internal server error, for (GET) [/events] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: (,List())]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:269)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:195)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:98)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$$anonfun$tryCompleteWith$1.apply(Promise.scala:76)
	at scala.concurrent.Promise$$anonfun$tryCompleteWith$1.apply(Promise.scala:76)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: (,List())
	at scala.sys.package$.error(package.scala:27)
	at reactivemongo.play.json.JSONSerializationPack$.deserialize(package.scala:470)
	at reactivemongo.play.json.JSONSerializationPack$.deserialize(package.scala:437)
	at reactivemongo.api.SerializationPack$class.readAndDeserialize(serializationpack.scala:28)
	at reactivemongo.play.json.JSONSerializationPack$.readAndDeserialize(package.scala:437)
	at reactivemongo.core.protocol.ReplyDocumentIterator$$anon$1.next(protocol.scala:377)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$6.apply(cursor.scala:646)
	at scala.util.Try$.apply(Try.scala:192)
	at reactivemongo.api.DefaultCursor$Impl$class.go$1(cursor.scala:646)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldWhileM$2.apply(cursor.scala:666)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldWhileM$2.apply(cursor.scala:666)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldBulksM$2.apply(cursor.scala:630)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldBulksM$2.apply(cursor.scala:628)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses.procResp(cursor.scala:792)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses$$anonfun$procResponses$3.apply(cursor.scala:828)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses$$anonfun$procResponses$3.apply(cursor.scala:827)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 13 common frames omitted
2016-11-24 12:04:12,609 [INFO] from application in ForkJoinPool-4-worker-13 - ReactiveMongoApi stopping...
2016-11-24 12:04:12,623 [INFO] from application in ForkJoinPool-4-worker-9 - ReactiveMongoApi connections stopped. [Success(Closed)]
2016-11-24 12:04:12,659 [INFO] from application in ForkJoinPool-4-worker-13 - ApplicationTimer demo: Stopping application at 2016-11-24T11:04:12.659Z after 591s.
2016-11-24 12:04:12,772 [INFO] from application in application-akka.actor.default-dispatcher-3 - ApplicationTimer demo: Starting application at 2016-11-24T11:04:12.772Z.
2016-11-24 12:04:12,827 [INFO] from application in application-akka.actor.default-dispatcher-3 - Resolving database...
2016-11-24 12:04:12,835 [INFO] from application in application-akka.actor.default-dispatcher-3 - ReactiveMongoApi successfully configured with DB 'gdeed'! Servers:
		[localhost:27017]
2016-11-24 12:04:12,840 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-3 - Application started (Dev)
2016-11-24 12:04:41,314 [ERROR] from application in application-akka.actor.default-dispatcher-6 - 

! @726nc9122 - Internal server error, for (GET) [/events] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: (,List())]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:269)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:195)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:98)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$$anonfun$tryCompleteWith$1.apply(Promise.scala:76)
	at scala.concurrent.Promise$$anonfun$tryCompleteWith$1.apply(Promise.scala:76)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: (,List())
	at scala.sys.package$.error(package.scala:27)
	at reactivemongo.play.json.JSONSerializationPack$.deserialize(package.scala:470)
	at reactivemongo.play.json.JSONSerializationPack$.deserialize(package.scala:437)
	at reactivemongo.api.SerializationPack$class.readAndDeserialize(serializationpack.scala:28)
	at reactivemongo.play.json.JSONSerializationPack$.readAndDeserialize(package.scala:437)
	at reactivemongo.core.protocol.ReplyDocumentIterator$$anon$1.next(protocol.scala:377)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$6.apply(cursor.scala:646)
	at scala.util.Try$.apply(Try.scala:192)
	at reactivemongo.api.DefaultCursor$Impl$class.go$1(cursor.scala:646)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldWhileM$2.apply(cursor.scala:666)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldWhileM$2.apply(cursor.scala:666)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldBulksM$2.apply(cursor.scala:630)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldBulksM$2.apply(cursor.scala:628)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses.procResp(cursor.scala:792)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses$$anonfun$procResponses$3.apply(cursor.scala:828)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses$$anonfun$procResponses$3.apply(cursor.scala:827)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 13 common frames omitted
2016-11-24 12:04:41,432 [ERROR] from application in application-akka.actor.default-dispatcher-7 - 

! @726nc916g - Internal server error, for (GET) [/events] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: (,List())]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:269)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:195)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:98)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$$anonfun$tryCompleteWith$1.apply(Promise.scala:76)
	at scala.concurrent.Promise$$anonfun$tryCompleteWith$1.apply(Promise.scala:76)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: (,List())
	at scala.sys.package$.error(package.scala:27)
	at reactivemongo.play.json.JSONSerializationPack$.deserialize(package.scala:470)
	at reactivemongo.play.json.JSONSerializationPack$.deserialize(package.scala:437)
	at reactivemongo.api.SerializationPack$class.readAndDeserialize(serializationpack.scala:28)
	at reactivemongo.play.json.JSONSerializationPack$.readAndDeserialize(package.scala:437)
	at reactivemongo.core.protocol.ReplyDocumentIterator$$anon$1.next(protocol.scala:377)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$6.apply(cursor.scala:646)
	at scala.util.Try$.apply(Try.scala:192)
	at reactivemongo.api.DefaultCursor$Impl$class.go$1(cursor.scala:646)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldWhileM$2.apply(cursor.scala:666)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldWhileM$2.apply(cursor.scala:666)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldBulksM$2.apply(cursor.scala:630)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldBulksM$2.apply(cursor.scala:628)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses.procResp(cursor.scala:792)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses$$anonfun$procResponses$3.apply(cursor.scala:828)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses$$anonfun$procResponses$3.apply(cursor.scala:827)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 13 common frames omitted
2016-11-24 12:06:30,694 [INFO] from application in ForkJoinPool-4-worker-7 - ReactiveMongoApi stopping...
2016-11-24 12:06:30,705 [INFO] from application in ForkJoinPool-4-worker-5 - ReactiveMongoApi connections stopped. [Success(Closed)]
2016-11-24 12:06:30,724 [INFO] from application in ForkJoinPool-4-worker-7 - ApplicationTimer demo: Stopping application at 2016-11-24T11:06:30.724Z after 138s.
2016-11-24 12:06:30,827 [INFO] from application in application-akka.actor.default-dispatcher-2 - ApplicationTimer demo: Starting application at 2016-11-24T11:06:30.827Z.
2016-11-24 12:06:30,881 [INFO] from application in application-akka.actor.default-dispatcher-2 - Resolving database...
2016-11-24 12:06:30,887 [INFO] from application in application-akka.actor.default-dispatcher-2 - ReactiveMongoApi successfully configured with DB 'gdeed'! Servers:
		[localhost:27017]
2016-11-24 12:06:30,891 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-2 - Application started (Dev)
2016-11-24 12:06:31,022 [ERROR] from application in application-akka.actor.default-dispatcher-4 - 

! @726ncf79h - Internal server error, for (GET) [/events] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: (,List())]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:269)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:195)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:98)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$$anonfun$tryCompleteWith$1.apply(Promise.scala:76)
	at scala.concurrent.Promise$$anonfun$tryCompleteWith$1.apply(Promise.scala:76)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: (,List())
	at scala.sys.package$.error(package.scala:27)
	at reactivemongo.play.json.JSONSerializationPack$.deserialize(package.scala:470)
	at reactivemongo.play.json.JSONSerializationPack$.deserialize(package.scala:437)
	at reactivemongo.api.SerializationPack$class.readAndDeserialize(serializationpack.scala:28)
	at reactivemongo.play.json.JSONSerializationPack$.readAndDeserialize(package.scala:437)
	at reactivemongo.core.protocol.ReplyDocumentIterator$$anon$1.next(protocol.scala:377)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$6.apply(cursor.scala:646)
	at scala.util.Try$.apply(Try.scala:192)
	at reactivemongo.api.DefaultCursor$Impl$class.go$1(cursor.scala:646)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldWhileM$2.apply(cursor.scala:666)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldWhileM$2.apply(cursor.scala:666)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldBulksM$2.apply(cursor.scala:630)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$foldBulksM$2.apply(cursor.scala:628)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses.procResp(cursor.scala:792)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses$$anonfun$procResponses$3.apply(cursor.scala:828)
	at reactivemongo.api.DefaultCursor$Impl$FoldResponses$$anonfun$procResponses$3.apply(cursor.scala:827)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 13 common frames omitted
2016-11-24 12:11:41,905 [INFO] from application in ForkJoinPool-4-worker-5 - ReactiveMongoApi stopping...
2016-11-24 12:11:41,919 [INFO] from application in ForkJoinPool-4-worker-1 - ReactiveMongoApi connections stopped. [Success(Closed)]
2016-11-24 12:11:41,934 [INFO] from application in ForkJoinPool-4-worker-5 - ApplicationTimer demo: Stopping application at 2016-11-24T11:11:41.934Z after 311s.
2016-11-24 12:11:42,079 [INFO] from application in application-akka.actor.default-dispatcher-2 - ApplicationTimer demo: Starting application at 2016-11-24T11:11:42.078Z.
2016-11-24 12:11:42,158 [INFO] from application in application-akka.actor.default-dispatcher-2 - Resolving database...
2016-11-24 12:11:42,169 [INFO] from application in application-akka.actor.default-dispatcher-2 - ReactiveMongoApi successfully configured with DB 'gdeed'! Servers:
		[localhost:27017]
2016-11-24 12:11:42,174 [INFO] from play.api.Play in application-akka.actor.default-dispatcher-2 - Application started (Dev)
